version: '3'
services:
  mongo:
    image: mongo:5.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mamae
      MONGO_INITDB_USERNAME: readwrite
      MONGO_INITDB_PASSWORD: pwd
      MONGO_INITDB_DATABASE: laercio
    ports:
      - "27017:27017"
    volumes:
      # montando o mongo localmente no volume criado ali embaixo
      - mongo-vol:/data/db
      #  um script que start o mongo criando dois usuarios a partir das env vars ali em cima
      - ./start-mongo.sh:/docker-entrypoint-initdb.d/start-mongo.sh
      - ./mongod.conf:/etc/mongod.conf
volumes:
  mongo-vol:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /mnt/disks/mongo_data # aqui vc coloca o path do volume que vc criou no GCP